### ISSUE TITLE
CProxy_CkArray(aid).ckDestroy gives segfault when using bound array

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#1011]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1011*

---
No body.

**Comment by harshithamenon** [comment]
*Original date: 2016-03-16 04:09:40*

---
Stack trace

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000102f40020
0x0000000100286ba6 in CkLocMgr::deleteManager (this=0x102e0a620, id={_gid = {idx = 14}}, mgr=0x102e0b3f0) at cklocation.C:2729
2729      while (cur->mgr != mgr) {
(gdb) bt
#0  0x0000000100286ba6 in CkLocMgr::deleteManager (this=0x102e0a620, id={_gid = {idx = 14}}, mgr=0x102e0b3f0) at cklocation.C:2729
#1  0x00000001002a67f0 in CkArray::ckDestroy (this=0x102e0b1d0) at ckarray.C:1693
#2  0x00000001002a8b5a in CkIndex_CkArray::_call_ckDestroy_void (impl_msg=0x106301610, impl_obj_void=0x102e0b1d0) at CkArray.def.h:775
#3  0x00000001002608d1 in CkDeliverMessageFree (epIdx=75, msg=0x106301610, obj=0x102e0b1d0) at ck.C:593
#4  0x000000010026100e in _invokeEntryNoTrace (epIdx=75, env=0x1063015c0, obj=0x102e0b1d0) at ck.C:637
#5  0x0000000100265ac1 in _invokeEntry (epIdx=75, env=0x1063015c0, obj=0x102e0b1d0) at ck.C:648
#6  0x0000000100263545 in _deliverForBocMsg (ck=0x102e01440, epIdx=75, env=0x1063015c0, obj=0x102e0b1d0) at ck.C:1097
#7  0x0000000100262446 in _processForBocMsg (ck=0x102e01440, env=0x1063015c0) at ck.C:1109
#8  0x0000000100262152 in _processHandler (converseMsg=0x1063015c0, ck=0x102e01440) at ck.C:1251

**Comment by harshithamenon** [comment]
*Original date: 2016-03-16 04:24:35*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1113/~~ https://github.com/UIUC-PPL/charm/commit/53819195252795af1c2722595c404d22bc1aa101
