### ISSUE TITLE
Fix autobuild failure in gni-crayxc-smp caused by examples/rdma/simpleRdma because of freeing a Smsg and then reusing it in the machine layer. 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1623]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1623*

---
Autobuild failure: http://charm.cs.illinois.edu/autobuild/old.2017_06_30__01_01/gni-crayxc-smp.txt

The crash has the following stack trace:

#0  0x000000f800000000 in ?? ()
#1  0x00000000201479d5 in PumpNetworkSmsg () at machine.c:2307
#2  0x00000000201495f0 in LrtsAdvanceCommunication (whileidle=whileidle`entry=1) at machine.c:3502
#3  0x000000002014963e in AdvanceCommunication (whenidle=1) at machine-common-core.c:1317
#4  CommunicationServer (sleepTime=<optimized out>) at machine-common-core.c:1341
#5  0x0000000020149a1f in CommunicationServerThread (sleepTime=5) at machine-common-core.c:1360
#6  ConverseRunPE (everReturn=everReturn`entry=0) at machine-common-core.c:1292
#7  0x0000000020149ee6 in call_startfn (vindex=0x1) at machine-smp.c:408
#8  0x000000002018e0c6 in start_thread (arg=<optimized out>) at pthread_create.c:301
#9  0x00000000204ed379 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#10 0x0000000000000000 in ?? ()
(gdb) frame 1
#1  0x00000000201479d5 in PumpNetworkSmsg () at machine.c:2307
2307	                ack->fnPtr(ack->token);

The ack (of type CmiGNIAckOp_t) is used even after it is released by SmsgRelease. 

The GNI Smsg API requires the message to not be used after a call to Gni_SmsgRelease. (and it needs to be either processed or copied before making the call to Gni_SmsgRelease).

**Comment by nitbhat** [comment]
*Original date: 2017-06-30 21:50:57*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2743/~~ https://github.com/UIUC-PPL/charm/commit/9823be9c42ef44bfd530ff39feb7f03665be88b7

Copied the received ack message into a new message before the call to Gni_SmsgRelease. (and used the new message thereafter).
