### ISSUE TITLE
Converse machinetest hangs for gni-crayxe-smp and verbs-linux-x86_64-smp

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1815]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1815*

---
These failures were found in the nightly build after ~~https://charm.cs.illinois.edu/gerrit/#/c/3478/~~ https://github.com/UIUC-PPL/charm/commit/c99900c04d249d18c3dbc6c8747dd490c40f23ee was merged. 

Hang stacktrace: 
```
(gdb) bt
#0  pthread_cond_wait ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000002000ffe6 in CmiNodeBarrierCount (nThreads=2) at machine-smp.c:344
#2  0x000000002001035b in CmiNodeAllBarrier () at machine-smp.c:555
#3  0x00000000200460bc in LrtsInitCpuTopo (argv=0x7fffffff6578)
    at cputopology.C:550
#4  0x00000000200461fc in CmiInitCPUTopology (argv=0x7fffffff6578)
    at cputopology.C:694
#5  0x000000002000c64e in mymain (argc=2, argv=0x7fffffff6578) at pingall.C:183
#6  0x0000000020013ef0 in ConverseRunPE (everReturn=0)
    at machine-common-core.c:1502
#7  0x00000000200139df in ConverseInit (argc=2, argv=0x7fffffff6578, 
    fn=0x2000b402 <mymain(int, char**)>, usched=0, initret=0)
    at machine-common-core.c:1398
#8  0x000000002000c78e in main (argc=2, argv=0x7fffffff6578) at pingall.C:203

```

**Comment by nitbhat** [comment]
*Original date: 2018-03-02 21:57:56*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3795/~~ https://github.com/UIUC-PPL/charm/commit/2985f4a02c11334d8c1cf5142dd4abc955aa520c
