### ISSUE TITLE
awakenfn function pointer causes thread migration failure across logical nodes in ASLR environments

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#2280]
Converse threads call a function pointer named `awakenfn` and serialize it raw.

`src/conv-core/threads.C:665:  pup_bytes(p,&t->awakenfn,sizeof(t->awakenfn));`

This is incompatible with migration across logical nodes in ASLR environments and will cause crashes.

one-liner to reproduce the problem: `./build AMPI netlrts-linux-x86_64-smp -j8 -g3 && pushd netlrts-linux-x86_64-smp/tests/ampi/megampi/ && make OPTS="-g3" -Bj8 && ./charmrun ./pgm +p2 +vp2 ++debug ++debug-commands "set disable-randomization off \n r"`

<pre>
CharmLB> RandCentLB created.
[0] Testing: Testing...

Thread 1 "pgm" received signal SIGSEGV, Segmentation fault.
0x00005575c4422701 in ?? ()
(gdb) bt
#0  0x00005575c4422701 in ?? ()
#1  0x00005636e12be4dd in CthAwaken (th=0x5636e3133da0) at threads.C:904
#2  0x00005636e1113830 in TCharm::start (this=0x5636e3192050) at tcharm_impl.h:274
#3  0x00005636e110e070 in TCharm::ResumeFromSync (this=0x5636e3192050) at tcharm.C:524
#4  0x00005636e11daf72 in CkMigratable::staticResumeFromSync (data=0x5636e3192050) at cklocation.C:1764
#5  0x00005636e128d408 in LocalBarrier::ResumeClients (this=0x5636e3180aa8) at LBDBManager.C:666
#6  0x00005636e126f796 in LBDB::ResumeClients (this=0x5636e31809f0) at LBDBManager.h:207
#7  0x00005636e126ed87 in LDResumeClients (_db=...) at lbdb.C:470
#8  0x00005636e1256d07 in LBDatabase::ResumeClients (this=0x5636e3180980) at LBDatabase.C:603
#9  0x00005636e129bb3c in CentralLB::ResumeClients (this=0x5636e318ab80, balancing=1) at CentralLB.C:1425
#10 0x00005636e12a3dcd in CkIndex_CentralLB::_call_ResumeClients_marshall11 (impl_msg=0x5636e3192550, impl_obj_void=0x5636e318ab80) at CentralLB.def.h:1946
#11 0x00005636e11b0e88 in CkDeliverMessageFree (epIdx=195, msg=0x5636e3192550, obj=0x5636e318ab80) at ck.C:569
#12 0x00005636e11b0fdf in _invokeEntryNoTrace (epIdx=195, env=0x5636e3192500, obj=0x5636e318ab80) at ck.C:620
#13 0x00005636e11b10f3 in _invokeEntry (epIdx=195, env=0x5636e3192500, obj=0x5636e318ab80) at ck.C:631
#14 0x00005636e11b27dd in _deliverForBocMsg (ck=0x5636e3161200, epIdx=195, env=0x5636e3192500, obj=0x5636e318ab80) at ck.C:1089
#15 0x00005636e11b28af in _processForBocMsg (ck=0x5636e3161200, env=0x5636e3192500) at ck.C:1111
#16 0x00005636e11b2edc in _processHandler (converseMsg=0x5636e3192500, ck=0x5636e3161200) at ck.C:1284
#17 0x00005636e12cae76 in CmiHandleMessage (msg=0x5636e3192500) at convcore.C:1656
#18 0x00005636e12cb23b in CsdScheduleForever () at convcore.C:1914
#19 0x00005636e12cb181 in CsdScheduler (maxmsgs=-1) at convcore.C:1842
#20 0x00005636e12c2c4b in ConverseRunPE (everReturn=0) at machine-common-core.C:1596
#21 0x00005636e12c2838 in ConverseInit (argc=1, argv=0x7ffe8a98e458, fn=0x5636e11a0c67 <_initCharm(int, char**)>, usched=0, initret=0) at machine-common-core.C:1491
#22 0x00005636e11a329f in charm_main (argc=1, argv=0x7ffe8a98e458) at init.C:1845
#23 0x00005636e1199c5f in main (argc=1, argv=0x7ffe8a98e458) at main.C:5
(gdb) f 1
#1  0x00005636e12be4dd in CthAwaken (th=0x5636e3133da0) at threads.C:904
904       B(th)->awakenfn(B(th)->token, CQS_QUEUEING_FIFO, 0, 0);
(gdb) p B(th)->awakenfn
$1 = (CthAwkFn) 0x5575c4422701
</pre>

Related to #159, #2018

**Comment by evan-charmworks** [comment]
ASLR workarounds are in place, so closing.
