### ISSUE TITLE
pupping a proxy fails when restarting from a checkpoint

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2643]
ChaNGa has a chare array with a pup routine that has a line
```
p | pieces;
```
where pieces is declared
```
CProxy_TreePiece pieces;
```
That is, `pieces` is a proxy to the chare array.
On a restart from a checkpoint, one can get the following call stack:
```
#7  0x00000000005c2d12 in TreePiece::drift(double, int, int, double, double, int, bool, double, CkCallback const&) () at TreePiece.cpp:2124
#8  0x0000000000625efb in CkIndex_TreePiece::_call_drift_marshall60(void*, void*) () at ParallelGravity.def.h:19048
#9  0x000000000076f2d8 in CkDeliverMessageReadonly (epIdx=238, 
    msg=0x2b4821a7f340, obj=0x2b48c50a9c80) at cklists.h:224
#10 0x00000000007a3a1f in CkLocRec::invokeEntry(CkMigratable*, void*, int, bool) () at cklists.h:224
#11 0x00000000007d2483 in CkArrayBroadcaster::deliver(CkArrayMessage*, ArrayElement*, bool) () at cklists.h:224
#12 0x00000000007dec6f in CkArray::recvBroadcast(CkMessage*) ()
    at cklists.h:224
#13 0x0000000000770e13 in CkDeliverMessageFree (epIdx=63, msg=0x2b4821a7f340, 
    obj=obj@entry=0x2b48180402a0) at cklists.h:224
#14 0x0000000000771296 in _invokeEntryNoTrace (obj=0x2b48180402a0, 
    env=0x2b4821a7f2f0, epIdx=63) at ck.C:597
#15 _invokeEntry (epIdx=epIdx@entry=63, env=env@entry=0x2b4821a7f2f0, 
    obj=obj@entry=0x2b48180402a0) at ck.C:615
#16 0x00000000007769df in _deliverForBocMsg (obj=0x2b48180402a0, 
    env=0x2b4821a7f2f0, epIdx=63, ck=<optimized out>) at ck.C:1066
#17 _processForBocMsg (env=0x2b4821a7f2f0, ck=<optimized out>) at ck.C:1088
#18 _processHandler (converseMsg=<optimized out>, ck=<optimized out>)
    at ck.C:1245
#19 0x00000000008956f5 in CsdSchedulePoll ()
#20 0x000000000089586f in CsdScheduler ()
#21 0x000000000076d588 in CkLocalNodeBranch (groupID=...) at ck.C:501
#22 0x0000000000770631 in ckDelegatedTo (this=0x2b48c50aa110) at charm++.h:764
#23 CProxy::pup (this=0x2b48c50aa110, p=...) at ck.C:335
#24 0x00000000007d0bf1 in CProxy_ArrayBase::pup(PUP::er&) () at cklists.h:224
#25 0x00000000005c58ce in pup (p=..., this=0x2b48c50aa110)
    at ../charm/bin/../include/CkArray.decl.h:1222
#26 pup (p=..., this=0x2b48c50aa110) at ParallelGravity.decl.h:7176
#27 operator|<CProxy_TreePiece> (t=..., p=...)
    at ../charm/bin/../include/pup.h:994
#28 TreePiece::pup(PUP::er&) () at TreePiece.cpp:5741
#29 0x00000000007a4b92 in CkLocMgr::pupElementsFor(PUP::er&, CkLocRec*, CkElementCreation_t, bool) () at cklists.h:224
#30 0x00000000007a785b in CkLocMgr::resume(CkArrayIndex const&, unsigned long, PUP::er&, bool, bool) () at cklists.h:224
#31 0x0000000000821a55 in CkPupArrayElementsData(PUP::er&, int) ()
    at ckcheckpoint.C:593
#32 0x000000000082717c in CkRestartMain(char const*, CkArgMsg*) ()
    at ckcheckpoint.C:818
#33 0x0000000000765232 in _initCharm(int, char**) ()
#34 0x0000000000893086 in ConverseRunPE(int) () at machine-common-core.C:1595
#35 0x0000000000893826 in call_startfn (vindex=0x19) at machine-smp.C:379
#36 0x00002b47a4bb2dd5 in start_thread () from /lib64/libpthread.so.0
#37 0x00002b47a661802d in clone () from /lib64/libc.so.6
```
The top of the call stack is a call to a chare array entry method that ends badly because the TreePiece::pup() (stack slot 28 above) has not completed.  The problem arises because CkLocalNodeBranch() calls the scheduler.

**Comment by olawlor** [comment]
It's curious that CkLocalNodeBranch calls the scheduler! It only does this if the nodegroup doesn't exist yet (ck.C:493)
`void *CkLocalNodeBranch(CkGroupID groupID)
{
  void *retval;
  // we are called in a constructor
  if (CkpvAccess(_currentNodeGroupObj) && CkpvAccess(_currentGroup) == groupID)
    return CkpvAccess(_currentNodeGroupObj);
  while (NULL== (retval=_ckLocalNodeBranch(groupID)))
  { // Nodegroup hasn't finished being created yet-- schedule...
    CsdScheduler(0);
  }
  return retval;
}`

This 'feature' is from a 2003 commit by me: 
`Reorder nodegroup creation and CkLocal
to avoid race conditions during startup--
now leave nodegroups out of the group table
until they're fully constructed, and "block"
(by calling the scheduler) rather than returning
NULL. This makes the extra conditional processing
inside ckreduction redundant.
Orion Lawlor committed on Aug 29, 2003
`
It's not clear how to resolve this situation where you're pupping a nodegroup proxy before the nodegroup exists.  The local workaround seems reasonable to me.
