### ISSUE TITLE
glibc heap-allocates internal FILE buffers on first print

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#2814]
glibc internally allocates buffers for stdout and stderr the first time something is written to those file descriptors. UCX builds of #2531 expose an issue where these first print statements happen inside an AMPI rank with `-memory isomalloc` enabled, so these internal buffers are allocated locally for the rank, and if that rank migrates away, the pointers become invalid and the next write to the file descriptor will segfault inside glibc. It is unknown why this behavior is only exposed by this PR.

Here are example stack traces:

```gdb
Thread 1 "pgm" received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:288
288     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:288
#1  0x00007ffff77f0792 in _IO_new_file_xsputn (n=1, data=0x555555ae8610, f=<optimized out>) at fileops.c:1240
#2  _IO_new_file_xsputn (f=0x7ffff79496a0 <_IO_2_1_stdout_>, data=0x555555ae8610, n=1) at fileops.c:1201
#3  0x00007ffff77d7a42 in __vfprintf_internal (s=0x7ffff79496a0 <_IO_2_1_stdout_>, format=0x555555ae8610 "[%d] migrated from %d to %d\n", ap=ap@entry=0x2aaaa010fbf0, mode_flags=mode_flags@entry=0) at ../libio/libioP.h:948
#4  0x00007ffff77c2e1f in __printf (format=<optimized out>) at printf.c:33
#5  0x00005555558247fe in MPI_Tester::testMigrate (this=0x2aaaa010ff24) at test.C:302
#6  0x0000555555825171 in AMPI_Main_cpp (argc=1, argv=0x2aaaa00003c0) at test.C:506
#7  0x000055555589f540 in AMPI_threadstart (data=0x555555d09550) at ampi.C:1096
#8  0x0000555555825cb0 in startTCharmThread (msg=0x555555d09530) at tcharm.C:163
#9  0x0000555555a529dc in CthStartThread (arg=...) at threads.C:1836
#10 0x0000555555a52e4f in make_fcontext ()
#11 0x0000000000000000 in ?? ()
```

```gdb
Thread 1 "cxx-tlsglobals" received signal SIGSEGV, Segmentation fault.
memcpy () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:144
144     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  memcpy () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:144
#1  0x00007ffff77eb792 in _IO_new_file_xsputn (n=27, data=0x555555ae70c8, f=<optimized out>) at fileops.c:1240
#2  _IO_new_file_xsputn (f=0x7ffff79446a0 <_IO_2_1_stdout_>, data=0x555555ae70c8, n=27) at fileops.c:1201
#3  0x00007ffff77e0568 in __GI__IO_puts (str=0x555555ae70c8 "Beginning round of testing.") at libioP.h:948
#4  0x0000555555823a66 in perform_test_batch_ (failed=@0x40010ff24: 0, rank=@0x40010ff3c: 0, my_wth=@0x40010ff34: 0, operation=@0x40010ff2c: 1) at test-cxx.C:54
#5  0x00005555558238d8 in privatization_test_framework_ () at test.C:74
#6  0x0000555555823e22 in AMPI_Main_cpp (argc=1, argv=0x4000004c0) at test-cxx.C:186
#7  0x000055555589dfdc in AMPI_threadstart (data=0x555555cff150) at ampi.C:1096
#8  0x000055555582474c in startTCharmThread (msg=0x555555cff130) at tcharm.C:163
#9  0x0000555555a5167c in CthStartThread (arg=...) at threads.C:1836
#10 0x0000555555a51aef in make_fcontext ()
#11 0x0000000000000000 in ?? ()
```

**Comment by matthiasdiener** [comment]
Is this bug actually fixed?

**Comment by evan-charmworks** [comment]
> Is this bug actually fixed?

The original one, yes. My more recent post is similar but distinct. I will make a separate issue for it.
