### ISSUE TITLE
Fail to build with address sanitizer

### ISSUE THREAD

**Issue by HanatoK** [UIUC-PPL/charm#3790]
I am using the following command to build Charm++:
```
./build charm++ multicore-linux-x86_64 --with-production -j4 -g -fsanitize=address
```
but the compilation fails due to the following errors (it is too long so I upload them as an attachment instead):
[charm++_bug.txt](https://github.com/UIUC-PPL/charm/files/14619368/charm%2B%2B_bug.txt)

**Comment by matthiasdiener** [comment]
Thanks for the report! Most of these seem to come from charmxi:

```
==26147==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x7f2ab00fc1d8 in operator new(unsigned long) (/lib64/libasan.so.8+0xfc1d8) (BuildId: 752eb14d218b669aabc831998f712b1ece1d51e6)
    #1 0x45cda1 in xi::Entry::genClosure(xi::XStr&, bool) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x45cda1) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #2 0x45b953 in xi::Entry::genClosureEntryDecls(xi::XStr&) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x45b953) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #3 0x4819ec in xi::details::perElemGenC<xi::Member, xi::AstNode, xi::XStr&>::operator()(xi::Member*) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x4819ec) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #4 0x4815ea in xi::details::perElemGenC<xi::Member, xi::AstNode, xi::XStr&> std::for_each<std::_List_iterator<xi::Member*>, xi::details::perElemGenC<xi::Member, xi::AstNode, xi::XStr&> >(std::_List_iterator<xi::Member*>, std::_List_iterator<xi::Member*>, xi::details::perElemGenC<xi::Member, xi::AstNode, xi::XStr&>) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x4815ea) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #5 0x48128c in xi::details::perElemGenC<xi::Member, xi::AstNode, xi::XStr&>::perElemGenC(std::__cxx11::list<xi::Member*, std::allocator<xi::Member*> >&, xi::XStr&, void (xi::AstNode::*)(xi::XStr&), void (*)(xi::XStr&)) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x48128c) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #6 0x480ef8 in void xi::details::perElemGen<xi::Member, xi::AstNode, xi::XStr>(std::__cxx11::list<xi::Member*, std::allocator<xi::Member*> >&, xi::XStr&, void (xi::AstNode::*)(xi::XStr&), void (*)(xi::XStr&)) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x480ef8) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #7 0x480518 in xi::AstChildren<xi::Member>::genClosureEntryDecls(xi::XStr&) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x480518) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #8 0x43fb34 in xi::Chare::genClosureEntryDecls(xi::XStr&) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x43fb34) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #9 0x43ea7b in xi::Chare::genDecls(xi::XStr&) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x43ea7b) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #10 0x44d4ec in xi::details::perElemGenC<xi::Construct, xi::AstNode, xi::XStr&>::operator()(xi::Construct*) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x44d4ec) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #11 0x44d2ae in xi::details::perElemGenC<xi::Construct, xi::AstNode, xi::XStr&> std::for_each<std::_List_iterator<xi::Construct*>, xi::details::perElemGenC<xi::Construct, xi::AstNode, xi::XStr&> >(std::_List_iterator<xi::Construct*>, std::_List_iterator<xi::Construct*>, xi::details::perElemGenC<xi::Construct, xi::AstNode, xi::XStr&>) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x44d2ae) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #12 0x44d190 in xi::details::perElemGenC<xi::Construct, xi::AstNode, xi::XStr&>::perElemGenC(std::__cxx11::list<xi::Construct*, std::allocator<xi::Construct*> >&, xi::XStr&, void (xi::AstNode::*)(xi::XStr&), void (*)(xi::XStr&)) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x44d190) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #13 0x44cf82 in void xi::details::perElemGen<xi::Construct, xi::AstNode, xi::XStr>(std::__cxx11::list<xi::Construct*, std::allocator<xi::Construct*> >&, xi::XStr&, void (xi::AstNode::*)(xi::XStr&), void (*)(xi::XStr&)) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x44cf82) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #14 0x44cba8 in xi::AstChildren<xi::Construct>::genDecls(xi::XStr&) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x44cba8) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #15 0x46abc5 in xi::Module::generate() (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x46abc5) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #16 0x481a7d in xi::details::perElemC<xi::Module, xi::Module>::operator()(xi::Module*) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x481a7d) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #17 0x48166e in xi::details::perElemC<xi::Module, xi::Module> std::for_each<std::_List_iterator<xi::Module*>, xi::details::perElemC<xi::Module, xi::Module> >(std::_List_iterator<xi::Module*>, std::_List_iterator<xi::Module*>, xi::details::perElemC<xi::Module, xi::Module>) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x48166e) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #18 0x4812fa in xi::details::perElemC<xi::Module, xi::Module>::perElemC(std::__cxx11::list<xi::Module*, std::allocator<xi::Module*> >&, void (xi::Module::*)()) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x4812fa) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #19 0x480f76 in void xi::details::perElem<xi::Module, xi::Module>(std::__cxx11::list<xi::Module*, std::allocator<xi::Module*> >&, void (xi::Module::*)()) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x480f76) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #20 0x482e97 in xi::AstChildren<xi::Module>::recursev(void (xi::Module::*)()) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x482e97) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #21 0x4824bb in processAst(xi::AstChildren<xi::Module>*, bool, bool, int, int, char*, char*) (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x4824bb) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #22 0x48289d in main (/home/hanatok/HDD/software/charm/multicore-linux-x86_64/bin/charmxi+0x48289d) (BuildId: 98d36330c3db559c4b70050b5e643f10aab0796a)
    #23 0x7f2aaf82a1ef in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```
