### ISSUE TITLE
Message logging fails to deliver chare messages through VidBlock

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#388]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/388*

---
Running megatest on 1 PE results in the following backtrace/debug data:

```
#3  0x00000000007095e1 in CmiAbort (message=0x765980 "Send to out-of-bounds processor!") at machine.c:622
#4  0x000000000070db8f in DeliverOutgoingMessage (ogm=0x12110e0) at machine.c:1915
#5  0x000000000070de91 in CmiGeneralSend (pe=-1, size=2560, freemode=70, data=0x1257b00 "") at machine.c:2138
#6  0x000000000070df9d in CmiFreeSendFn (p=-1, s=2560, m=0x1257b00 "") at machine.c:2176
#7  0x0000000000711071 in CmiSyncVectorSend (destPE=-1, n=2, sizes=0xaefda0, msgs=0xaefe00) at convcore.c:2190
#8  0x00000000006a584a in sendMsg (sender=..., recver=..., destPE=-1, entry=0x12110b0, SN=1, TN=0, resend=0) at ckcausalmlog.C:903
#9  0x00000000006a55b9 in sendCommonMsg (recver=..., _env=0x1202530, destPE=-1, _infoIdx=33) at ckcausalmlog.C:819
#10 0x00000000006a5238 in sendChareMsg (env=0x1202530, destPE=-1, _infoIdx=33, pCid=0x7fffffffdec0) at ckcausalmlog.C:730
#11 0x000000000061fa33 in CkSendMsg (entryIdx=189, msg=0x12025b8, pCid=0x7fffffffdec0, opts=0) at ck.C:1636
#12 0x00000000006315bd in CkCallback::send (this=0x7fffffffdeb0, msg=0x12025b8) at ckcallback.C:229
#13 0x00000000005f0fa6 in callbackCoord::send (this=0x11f42e0, c=...) at callback.C:86
#14 0x00000000005f113b in callbackCoord::next (this=0x11f42e0) at callback.C:99
#15 0x00000000005f191a in callbackCoord (this=0x11f42e0) at callback.C:139
#16 0x00000000005eba80 in CkIndex_callbackCoord::_call_callbackCoord_void (impl_msg=0x11f4298, impl_obj_void=0x11f42e0) at callback.def.h:181
#17 0x000000000061d0bd in CkDeliverMessageFree (epIdx=185, msg=0x11f4298, obj=0x11f42e0) at ck.C:593
#18 0x000000000061d217 in _invokeEntryNoTrace (epIdx=185, env=0x11f4210, obj=0x11f42e0) at ck.C:637
#19 0x000000000061d333 in _invokeEntry (epIdx=185, env=0x11f4210, obj=0x11f42e0) at ck.C:648
#20 0x000000000061e3e0 in _processNewVChareMsg (ck=0xab5d00, env=0x11f4210) at ck.C:964
#21 0x000000000061ef18 in _processHandler (converseMsg=0x11f4210, ck=0xab5d00) at ck.C:1265
#22 0x00000000007104a2 in CmiHandleMessage (msg=0x11f4210) at convcore.c:1624
#23 0x000000000071072c in CsdScheduleForever () at convcore.c:1852
#24 0x0000000000710659 in CsdScheduler (maxmsgs=-1) at convcore.c:1788
#25 0x000000000070e6fe in ConverseRunPE (everReturn=0) at machine.c:2666
#26 0x000000000070ebc4 in ConverseInit (argc=1, argv=0x7fffffffe608, fn=0x612109 <_initCharm(int, char**)>, usc=0, everReturn=0) at machine.c:2880
#27 0x000000000060cd33 in main (argc=1, argv=0x7fffffffe608) at main.C:18
(gdb) f 12
#12 0x00000000006315bd in CkCallback::send (this=0x7fffffffdeb0, msg=0x12025b8) at ckcallback.C:229
229			CkSendMsg(d.chare.ep,msg,&d.chare.id);
(gdb) p this->d.chare
$4 = {ep = 189, id = {onPE = -1, objPtr = 0x11f2600}, refnum = 0, hasRefnum = false}
```
In looking at `sendChareMsg()` in `ckmessagelogging.C` and `ckcausalmlog.C`, the code path for chare messages never checks that `destPE` is positive before using it as an outbound destination.

**Comment by xiangni** [comment]
*Original date: 2015-03-03 21:16:47*

---
When I tried to reproduce this error, message logging build of charm++ fails the megatest at a different place (hang at test 5 groupcast). Message logging protocol identifies each chare object by CkChareID, which essentially is its pointer. In megatest, two chares from different tests may have the same memory address. Thus the message logging protocol fails to identify the real source of each message, causing wrong determinates or messages not being delivered.

I think to fix the bug requires redesign of part of message logging protocol or wait until 64bit id. Esteban, could you please verify?

**Comment by ericjbohm** [comment]
mlog has been excised
