### ISSUE TITLE
AMPI pingpong example segfaults --with-production

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#597]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/597*

---
The pingpong example in charm/examples/ampi/pingpong segfaults when Charm/AMPI is built with the --with-production option. Without production it runs normally.
The pingpong examples are not run in the nightly regression tests.

Here's the output running on finesse, with net-linux-x86_64 version of charm:

```
finesse[pingpong]$ make test
../../../bin/charmc -language ampi -O3 -g  pingpong-1way.c -o pgm
mpicc -O3 -g  pingpong-1way.c -o pgm-mpi
./charmrun +p2 ./pgm 100000 16 +vp2
Charmrun> started all node programs in 1.019 seconds.
Converse/Charm++ Commit ID: v6.6.0-15-g2347d5e
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (16-way SMP).
Charm++> cpu topology info is gathered in 0.001 seconds.
------------- Processor 0 Exiting: Caught Signal ------------
Signal: segmentation violation
Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
[0] Stack Traceback:
  [0:0] +0x36150  [0x7ffff723f150]
  [0:1] _ZN15AmpiRequestListixEm+0x1e  [0x4c0f1a]
  [0:2] _ZN4ampi9ssend_ackEi+0x58  [0x4a02ae]
  [0:3] _ZN12CkIndex_ampi25_call_ssend_ack_marshall7EPvS0_+0x7b  [0x4b3e33]
  [0:4] CkDeliverMessageFree+0x28  [0x4dfa78]
  [0:5] _ZN14CkLocRec_local11invokeEntryEP12CkMigratablePvib+0x64  [0x500fd4]
  [0:6] _ZN14CkLocRec_local7deliverEP14CkArrayMessage11CkDeliver_ti+0x187  [0x5023b7]
  [0:7] _ZN8CkLocMgr7deliverEP9CkMessage11CkDeliver_ti+0x1cb  [0x4fd50b]
  [0:8] _Z15_processHandlerPvP11CkCoreState+0x558  [0x4e5228]
  [0:9] CsdScheduleForever+0x68  [0x56e8f8]
  [0:10] CsdScheduler+0x2d  [0x56ebdd]
  [0:11] ConverseInit+0xef1  [0x56d121]
  [0:12] main+0x27  [0x48b577]
  [0:13] __libc_start_main+0xed  [0x7ffff722a76d]
  [0:14]   [0x48bcf1]
Fatal error on PE 0> segmentation violation
make: *** [test] Error 1
```

**Comment by PhilMiller** [comment]
*Original date: 2014-11-04 20:59:51*

---
Add preformatted tags to make error report readable.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2015-01-26 21:51:11*

---
I can't reproduce the problem easily. I could reproduce it once, but it didn't happen again after rebuilding charm.

Is there any other condition for it to happen?

**Comment by stwhite91** [comment]
*Original date: 2015-02-09 19:49:33*

---
I am also having difficulty reproducing this bug now, but here is the gdb output and backtrace:

```
./charmrun +p2 ./pgm 100000 16 +vp2 ++debug

Starting program: /dcsdata/home/swhite/charm/examples/ampi/pingpong/pgm 100000 16 +vp2 ++debug
Converse/Charm++ Commit ID: v6.6.0-15-g2347d5e
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (16-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.

Program received signal SIGSEGV, Segmentation fault.
0x00000000004c0f1a in AmpiRequestList::operator[] (this=0x996128, n=136)
at ampiimpl.h:774
774 AmpiRequest* operator[](size_t n) { return block[n]; }


(gdb) bt
#0 0x00000000004c0f1a in AmpiRequestList::operator[] (this=0x996128, n=136)
at ampiimpl.h:774
#1 0x00000000004a02ae in ampi::ssend_ack (this=0x997860, sreq_idx=136)
at ampi.C:1821
#2 0x00000000004b3e33 in CkIndex_ampi::_call_ssend_ack_marshall7 (
impl_msg=0x992910, impl_obj_void=0x997860) at ampi.def.h:2339
#3 0x00000000004dfa78 in CkDeliverMessageFree ()
#4 0x0000000000500fd4 in CkLocRec_local::invokeEntry(CkMigratable*, void*, int, bool) ()
#5 0x00000000005023b7 in CkLocRec_local::deliver(CkArrayMessage*, CkDeliver_t, int) ()
#6 0x00000000004fd50b in CkLocMgr::deliver(CkMessage*, CkDeliver_t, int) ()
#7 0x00000000004e5228 in _processHandler(void*, CkCoreState*) ()
#8 0x000000000056e8f8 in CsdScheduleForever ()
#9 0x000000000056ebdd in CsdScheduler ()
#10 0x000000000056d121 in ConverseInit ()
#11 0x000000000048b577 in main ()

```

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2015-02-09 22:40:44*

---
I ran thread sanitizer on the example:

on humility:   ./build AMPI netlrts-linux-x86_64 smp clang tsan -j16 -O2 -g

Thread sanitizer reports some warnings in charm/converse initialization (false positive?) but nothing else. The program crashes though.

**Comment by PhilMiller** [comment]
*Original date: 2015-04-02 20:22:46*

---
Ehsan has moved on to Intel, so we're shifting this back to you.

**Comment by nitbhat** [comment]
*Original date: 2016-02-27 02:51:50*

---
Tried reproducing by running in a loop for ~ 1000 times. Couldn't reproduce this bug. 

Tried to reproduce this bug on humility with AMPI builds: 
1) ./build AMPI netlrts-linux-x86_64 -j8 --with-production -g
2) ./build AMPI netlrts-linux-x86_64 smp clang --with-production -j16 -O2 -g
