### ISSUE TITLE
AMPI hangs at MPI_Main for Fortran on BG/Q

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#649]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/649*

---
AMPI hangs for Fortran programs on BlueGene/Q systems immediately after calling the application's MPI_Main subroutine.
Here's the stack trace for a test AMPI Fortran code that has an empty MPI_Main subroutine.
Charm/AMPI were built on Vulcan (LLNL) with: ./build AMPI pamilrts-bluegeneq xlc -g -O0
And the test program was built with: ampif90 -g -O0 fort.f90 -o fort

```
#0  0x000000000167e07c in __mcount_internal (frompc=17248776, selfpc=16783752) at mcount.c:78
78	          while (atomic_compare_and_exchange_bool_acq (&p->mcount_hwthd, hwthd, -1));
(gdb) bt
#0  0x000000000167e07c in __mcount_internal (frompc=17248776, selfpc=16783752) at mcount.c:78
#1  0x000000000165ce78 in ._mcount ()
#2  0x0000000001001988 in mpi_main () at fort.f90:1
#3  0x0000000001073208 in AMPI_Fallback_Main (argc=1, argv=0x19c6696ca0) at ampi.C:487
#4  0x0000000001072cac in MPI_threadstart_t::start (this=0x19c6918e40) at ampi.C:663
#5  0x0000000001072e8c in AMPI_threadstart (data=0x19c678c820) at ampi.C:680
#6  0x000000000100514c in startTCharmThread (msg=0x19c678c800) at tcharm.C:162
#7  0x000000000109885c in CthStartThread (fn=`0x1934390: 0x10050f0 <startTCharmThread(TCharmInitMsg*)>, arg=0x19c678c800)
    at threads.c:1694
#8  0x0000000001098820 in ?? () at threads.c:663

```

**Comment by PhilMiller** [comment]
*Original date: 2015-01-23 21:08:34*

---
http://charm.cs.uiuc.edu/gerrit/#/c/476/
