### ISSUE TITLE
CkExit() crashes called from main chare constructor with `-tracemode projections`

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#948]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/948*

---
This exhibits as follows in `tests/charm++/{queue,topology}`:

```
#0  0x00007ffff7012cc9 in __GI_raise (sig=sig`entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff70160d8 in __GI_abort () at abort.c:89
#2  0x00000000005ece61 in charmrun_abort (s=0x639668 "Error! This group proxy has not been initialized!") at machine.c:997
#3  0x00000000005ec7d5 in LrtsAbort (message=0x639668 "Error! This group proxy has not been initialized!") at machine.c:539
#4  0x00000000005ec2a1 in CmiAbortHelper (source=0x64ee49 "Called CmiAbort", message=0x639668 "Error! This group proxy has not been initialized!", suggestion=0x0, tellDebugger=1, framesToSkip=0) at machine-common-core.c:1416
#5  0x00000000005ec2d0 in CmiAbort (message=0x639668 "Error! This group proxy has not been initialized!") at machine-common-core.c:1420
#6  0x000000000052950b in CProxy_Group::ckCheck (this=0x7fffffffe240) at charm++.h:780
#7  0x00000000006339c8 in CProxy_TraceProjectionsBOC::ckCheck (this=0x7fffffffe240) at TraceProjections.decl.h:1455
#8  0x000000000062e037 in CProxy_TraceProjectionsBOC::traceProjectionsParallelShutdown (this=0x7fffffffe240, impl_noname_7=0, impl_e_opts=0x0) at TraceProjections.def.h:1948
#9  0x0000000000623438 in TraceProjectionsExitHandler () at trace-projections.C:1867
#10 0x000000000050e8c1 in _exitHandler (env=0xa805a0) at init.C:521
#11 0x00000000005f2dc5 in CmiHandleMessage (msg=0xa805a0) at convcore.c:1633
#12 0x00000000005f3046 in CsdScheduleForever () at convcore.c:1861
#13 0x00000000005f2f77 in CsdScheduler (maxmsgs=-1) at convcore.c:1797
#14 0x000000000050f592 in CkExit () at init.C:923
#15 0x00000000005b74f4 in controlPointManager::doExitNow (this=0xa4e1e0) at controlPoints.C:929
#16 0x00000000005b7447 in controlPointManager::exitIfReady (this=0xa4e1e0) at controlPoints.C:916
#17 0x00000000005b78c9 in controlPointShutdown () at controlPoints.C:1235
#18 0x000000000050e8c1 in _exitHandler (env=0xaae7a0) at init.C:521
#19 0x00000000005f2dc5 in CmiHandleMessage (msg=0xaae7a0) at convcore.c:1633
#20 0x00000000005f3046 in CsdScheduleForever () at convcore.c:1861
#21 0x00000000005f2f77 in CsdScheduler (maxmsgs=-1) at convcore.c:1797
#22 0x000000000050f592 in CkExit () at init.C:923
#23 0x000000000050bf25 in main::main (this=0xa4e180, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at pgm.C:295
#24 0x000000000050b51a in CkIndex_main::_call_main_CkArgMsg (impl_msg=0xa4eb20, impl_obj_void=0xa4e180) at main.def.h:49
#25 0x00000000005103b0 in _initCharm (unused_argc=1, argv=0x7fffffffea48) at init.C:1452
#26 0x00000000005ec097 in ConverseRunPE (everReturn=0) at machine-common-core.c:1262
#27 0x00000000005ebfc8 in ConverseInit (argc=1, argv=0x7fffffffea48, fn=0x50f7c5 <_initCharm(int, char**)>, usched=0, initret=0) at machine-common-core.c:1180
#28 0x000000000050db7e in main (argc=1, argv=0x7fffffffea48) at main.C:18
```

Because of the wonky initialization order semantics, calling CkExit from the mainchare's constructor means that you get into code that expects initialization that hasn't happened yet to be done.

**Comment by PhilMiller** [comment]
*Original date: 2016-03-03 19:40:41*

---
https://charm.cs.illinois.edu/gerrit/#/c/1095/

**Comment by PhilMiller** [comment]
*Original date: 2016-05-05 16:45:38*

---
Posted patch needs substantial further work.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-12 20:35:29*

---
I've got most of a fix for this done. It will just short-circuit the exit-time code if initialization hasn't happened.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-12 20:54:58*

---
~~https://charm.cs.illinois.edu/gerrit/2389~~ https://github.com/UIUC-PPL/charm/commit/9fb4709c61477c422c1a76d93cbc4994e72331c6
